import * as Icon from "@mui/icons-material";

export const iconList = [
  { name: "home", label: "Home", icon: Icon.Home },
  { name: "shoppingCart", label: "Shopping Cart", icon: Icon.ShoppingCart },
  { name: "restaurant", label: "Restaurant", icon: Icon.Restaurant },
  { name: "commute", label: "Commute", icon: Icon.Commute },
  { name: "localHospital", label: "Hospital", icon: Icon.LocalHospital },
  { name: "school", label: "School", icon: Icon.School },
  { name: "fitnessCenter", label: "Fitness Center", icon: Icon.FitnessCenter },
  {
    name: "localGroceryStore",
    label: "Grocery Store",
    icon: Icon.LocalGroceryStore,
  },
  { name: "attachMoney", label: "Money", icon: Icon.AttachMoney },
  { name: "localAtm", label: "ATM", icon: Icon.LocalAtm },
  { name: "cardGiftcard", label: "Gift Card", icon: Icon.CardGiftcard },
  { name: "flight", label: "Flight", icon: Icon.Flight },
  { name: "build", label: "Build", icon: Icon.Build },
  { name: "pets", label: "Pets", icon: Icon.Pets },
  { name: "sportsEsports", label: "Esports", icon: Icon.SportsEsports },
  { name: "localLibrary", label: "Library", icon: Icon.LocalLibrary },
  { name: "localCafe", label: "Cafe", icon: Icon.LocalCafe },
  { name: "localBar", label: "Bar", icon: Icon.LocalBar },
  { name: "directionsCar", label: "Car", icon: Icon.DirectionsCar },
  { name: "childCare", label: "Child Care", icon: Icon.ChildCare },
  { name: "localMall", label: "Mall", icon: Icon.LocalMall },
  { name: "event", label: "Event", icon: Icon.Event },
  { name: "localMovies", label: "Movies", icon: Icon.LocalMovies },
  {
    name: "localLaundryService",
    label: "Laundry Service",
    icon: Icon.LocalLaundryService,
  },
  { name: "localPharmacy", label: "Pharmacy", icon: Icon.LocalPharmacy },
  { name: "localGasStation", label: "Gas Station", icon: Icon.LocalGasStation },
  { name: "localParking", label: "Parking", icon: Icon.LocalParking },
  { name: "localShipping", label: "Shipping", icon: Icon.LocalShipping },
  { name: "localTaxi", label: "Taxi", icon: Icon.LocalTaxi },
  { name: "localPhone", label: "Phone", icon: Icon.LocalPhone },
  { name: "localPostOffice", label: "Post Office", icon: Icon.LocalPostOffice },
  { name: "localPrintshop", label: "Printshop", icon: Icon.LocalPrintshop },
  { name: "localSee", label: "See", icon: Icon.LocalSee },
  {
    name: "localConvenienceStore",
    label: "Convenience Store",
    icon: Icon.LocalConvenienceStore,
  },
  { name: "localFlorist", label: "Florist", icon: Icon.LocalFlorist },
  { name: "localDrink", label: "Drink", icon: Icon.LocalDrink },
  { name: "localPizza", label: "Pizza", icon: Icon.LocalPizza },
  { name: "localPlay", label: "Play", icon: Icon.LocalPlay },
  { name: "localDining", label: "Dining", icon: Icon.LocalDining },
  { name: "localActivity", label: "Activity", icon: Icon.LocalActivity },
  { name: "localAirport", label: "Airport", icon: Icon.LocalAirport },
  { name: "localBank", label: "Bank", icon: Icon.AccountBalance },
  { name: "localBarber", label: "Barber", icon: Icon.ContentCut },
  { name: "localBooks", label: "Books", icon: Icon.AutoStories },
  { name: "localBus", label: "Bus", icon: Icon.DirectionsBus },
  { name: "localCarWash", label: "Car Wash", icon: Icon.LocalCarWash },
  { name: "localCasino", label: "Casino", icon: Icon.Casino },
  { name: "localChurch", label: "Church", icon: Icon.Church },
  { name: "localCity", label: "City", icon: Icon.LocationCity },
  { name: "localClothingStore", label: "Clothing Store", icon: Icon.Checkroom },
  { name: "localCoffeeShop", label: "Coffee Shop", icon: Icon.Coffee },
  {
    name: "localCommunityCenter",
    label: "Community Center",
    icon: Icon.People,
  },
  { name: "localCourt", label: "Court", icon: Icon.Gavel },
  { name: "localDoctor", label: "Doctor", icon: Icon.Vaccines },
  {
    name: "localElectrician",
    label: "Electrician",
    icon: Icon.ElectricalServices,
  },
  { name: "localEmergency", label: "Emergency", icon: Icon.Emergency },
  { name: "localFireStation", label: "Fire Station", icon: Icon.FireTruck },
  { name: "localHairSalon", label: "Hair Salon", icon: Icon.ContentCut },
  { name: "localHotel", label: "Hotel", icon: Icon.LocalHotel },
  { name: "store", label: "Store", icon: Icon.Store },
  { name: "localMechanic", label: "Mechanic", icon: Icon.HomeRepairService },
  { name: "medication", label: "Medication", icon: Icon.Medication },
  { name: "localMovieTheater", label: "Movie Theater", icon: Icon.Theaters },
  { name: "localMuseum", label: "Museum", icon: Icon.Museum },
  { name: "localMusic", label: "Music", icon: Icon.LibraryMusic },
  { name: "localPark", label: "Park", icon: Icon.Park },
  { name: "localPolice", label: "Police", icon: Icon.LocalPolice },
  { name: "localSchool", label: "School", icon: Icon.School },
  { name: "localSpa", label: "Spa", icon: Icon.Spa },
  { name: "localStadium", label: "Stadium", icon: Icon.Stadium },
  { name: "localSwimmingPool", label: "Swimming Pool", icon: Icon.Pool },
  { name: "localTrain", label: "Train ", icon: Icon.Train },
].sort((a, b) => a.label.localeCompare(b.label));
